version: "2"
services:
  app:
    build: .
    environment:
      VIRTUAL_HOST: api.sawdev.info
      LETSENCRYPT_HOST: api.sawdev.info
      LETSENCRYPT_EMAIL: sawlow81wt@gmail.com
    expose:
      - "80"
    restart: always

networks:
  default:
    external:
      name: common-networks